distortion: Rec
task_mode: mcRec    # joint_rec_sr / ref-rec/scsr /mcsr

train_dataset:
  dataset:
    name: ixi_dataset_Reconstruction
    args:
      modality1: T2   
      modality2: PD
      split: train
      list_dir: ./IXI_dataset/list_file_IXI_T2_PD
      data_dir: ./IXI_dataset/IXI-T2-PD-H5
      img_size: 256
      mask_type: random_uniform
      acceleration_rate: 4
    
  n_workers: 8
  batch_size: 1

  
val_dataset:
  dataset:
    name: ixi_dataset_Reconstruction
    args:
      modality1: T2   
      modality2: PD
      split: val
      list_dir: ./IXI_dataset/list_file_IXI_T2_PD
      data_dir: ./IXI_dataset/IXI-T2-PD-H5
      img_size: 256
      mask_type: random_uniform
      acceleration_rate: 4
    
  n_workers: 8
  batch_size: 1

model:
  name: tsfn6
  args:
    inp_channels: 1
    out_channels: 1
    dim: 64
    enc_blk_nums: [1, 1, 1]
    middle_blk_num: 6

epoch_max: 200
epoch_val: 1
epoch_save: 10

val_freq: !!float 1000
save_checkpoint_freq: !!float 5000

loss_pixel_criterion: l1

optimizer:
  name: adam
  args:
    lr: 1.e-4
    betas: [0.9, 0.99]

multi_step_lr:
  name: CosineAnnealingLR_Restart
  args: 
    T_period: [200200]
    restarts: [200200]
    weights: [1]
    eta_min: !!float 1e-5

path:
  pretrain_model_G: ~
  strict_load: False
  resume_state: ~


logger:
  print_freq: 10
  save_checkpoint_freq: !!float 5000

resume: ~
pre_train: ~
  